### ISSUE TITLE
Remove Nuget binary from sources

### ISSUE THREAD

**Issue by karolz-ms** [Azure/diagnostics-eventflow#402]
We have a Nuget binary checked in into our sources (`tools` folder). A better way would be to rely on a copy that exists in the build environment. 

The binary is used by `tools\restore.cmd` script. A straightforward attempt to replace the use with `dotnet restore` failed--the latter does not seem to properly restore the old-style signing projects that we use for binary and Nuget package signing.

**Comment by xiaomi7732** [comment]
Lesson learned. @karolz-ms, have you tried to use this build step to bring in the binary:

```yaml
        - task: NuGetToolInstaller@1
          inputs:
            versionSpec: 
            checkLatest: true
```
